### ISSUE TITLE
bc...

### ISSUE THREAD

**Issue by just-hack** [bhikandeshmukh/shark#2]
abe chutiye tere baap ne bhi kabhi code kia tha aisa developer me mere code me apna naam dala hai jhatu

**Comment by bhikandeshmukh** [comment]
.

**Comment by just-hack** [comment]
> abe chutiye tere baap ne bhi kabhi code kia tha aisa developer me mere code me apna naam dala hai jhatu

bol na jhatu kaha rehta hai tu

**Comment by graysuit** [comment]
@bhikandeshmukh 
hahaha, lol, 
delete this issue and block this rude person.
